### IBM TELECOM CHURN PREDICTION AND RFM SEGMENTATION PROJECT

#### Data Loading, Merging, and Cleaning

In [2]:
import pandas as pd

In [9]:
df_demographics = pd.read_excel('..\\data\\raw\\Telco_customer_churn_demographics.xlsx')
df_location = pd.read_excel('..\\data\\raw\\Telco_customer_churn_location.xlsx')
df_population = pd.read_excel('..\\data\\raw\\Telco_customer_churn_population.xlsx')
df_services = pd.read_excel('..\\data\\raw\\Telco_customer_churn_services.xlsx')
df_status = pd.read_excel('..\\data\\raw\\Telco_customer_churn_status.xlsx')

print("Demographics:", df_demographics.shape)
print("Location:", df_location.shape)
print("Population:", df_population.shape)
print("Services:", df_services.shape)
print("Status:", df_status.shape)

Demographics: (7043, 9)
Location: (7043, 9)
Population: (1671, 3)
Services: (7043, 30)
Status: (7043, 11)

In [10]:
df_demographics.head()

,Customer ID,Count,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents
0,8779-QRDMV,1,Male,78,No,Yes,No,No,0
1,7495-OOKFY,1,Female,74,No,Yes,Yes,Yes,1
2,1658-BYGOY,1,Male,71,No,Yes,No,Yes,3
3,4598-XLKNJ,1,Female,78,No,Yes,Yes,Yes,1
4,4846-WHAFZ,1,Female,80,No,Yes,Yes,Yes,1

In [11]:
df_status.head()

,Customer ID,Count,Quarter,Satisfaction Score,Customer Status,Churn Label,Churn Value,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,1,Q3,3,Churned,Yes,1,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,1,Q3,3,Churned,Yes,1,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,1,Q3,2,Churned,Yes,1,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,1,Q3,2,Churned,Yes,1,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,1,Q3,2,Churned,Yes,1,67,2793,Price,Extra data charges

In [12]:
df_status['Churn Value'].value_counts()

Churn Value
0    5174
1    1869
Name: count, dtype: int64

In [15]:
df_services.head()

,Customer ID,Count,Quarter,Referred a Friend,Number of Referrals,Tenure in Months,Offer,Phone Service,Avg Monthly Long Distance Charges,Multiple Lines,...,Unlimited Data,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
0,8779-QRDMV,1,Q3,No,0,1,NaN,No,0.00,No,...,No,Month-to-Month,Yes,Bank Withdrawal,39.65,39.65,0.00,20,0.00,59.65
1,7495-OOKFY,1,Q3,Yes,1,8,Offer E,Yes,48.85,Yes,...,Yes,Month-to-Month,Yes,Credit Card,80.65,633.30,0.00,0,390.80,1024.10
2,1658-BYGOY,1,Q3,No,0,18,Offer D,Yes,11.33,Yes,...,Yes,Month-to-Month,Yes,Bank Withdrawal,95.45,1752.55,45.61,0,203.94,1910.88
3,4598-XLKNJ,1,Q3,Yes,1,25,Offer C,Yes,19.76,No,...,Yes,Month-to-Month,Yes,Bank Withdrawal,98.50,2514.50,13.43,0,494.00,2995.07
4,4846-WHAFZ,1,Q3,Yes,1,37,Offer C,Yes,6.33,Yes,...,Yes,Month-to-Month,Yes,Bank Withdrawal,76.50,2868.15,0.00,0,234.21,3102.36

In [16]:
df_services.shape

(7043, 30)

In [17]:
df_services.dtypes

Customer ID                              str
Count                                  int64
Quarter                                  str
Referred a Friend                        str
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                    str
Phone Service                            str
Avg Monthly Long Distance Charges    float64
Multiple Lines                           str
Internet Service                         str
Internet Type                            str
Avg Monthly GB Download                int64
Online Security                          str
Online Backup                            str
Device Protection Plan                   str
Premium Tech Support                     str
Streaming TV                             str
Streaming Movies                         str
Streaming Music                          str
Unlimited Data                           str
Contract                                 str
Paperless Billing                        str
Payment Method                           str
Monthly Charge                       float64
Total Charges                        float64
Total Refunds                        float64
Total Extra Data Charges               int64
Total Long Distance Charges          float64
Total Revenue                        float64
dtype: object

In [18]:
df_services.isnull().sum()

Customer ID                             0
Count                                   0
Quarter                                 0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download                 0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
dtype: int64

In [19]:
df_status.isnull().sum()

Customer ID              0
Count                    0
Quarter                  0
Satisfaction Score       0
Customer Status          0
Churn Label              0
Churn Value              0
Churn Score              0
CLTV                     0
Churn Category        5174
Churn Reason          5174
dtype: int64

In [21]:
df_demographics = df_demographics.drop(columns=['Count'])
df_services = df_services.drop(columns=['Count', 'Quarter'])
df_status = df_status.drop(columns=['Count', 'Quarter'])
df_location = df_location.drop(columns=['Count'])

df = df_demographics.merge(df_services, on='Customer ID', how='left')
df = df.merge(df_status, on='Customer ID', how='left')
df = df.merge(df_location, on='Customer ID', how='left')

print(df.shape)

(7043, 50)

In [22]:
df.head()

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Referred a Friend,Number of Referrals,...,CLTV,Churn Category,Churn Reason,Country,State,City,Zip Code,Lat Long,Latitude,Longitude
0,8779-QRDMV,Male,78,No,Yes,No,No,0,No,0,...,5433,Competitor,Competitor offered more data,United States,California,Los Angeles,90022,"34.02381, -118.156582",34.023810,-118.156582
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,Yes,1,...,5302,Competitor,Competitor made better offer,United States,California,Los Angeles,90063,"34.044271, -118.185237",34.044271,-118.185237
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,No,0,...,3179,Competitor,Competitor made better offer,United States,California,Los Angeles,90065,"34.108833, -118.229715",34.108833,-118.229715
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,Yes,1,...,5337,Dissatisfaction,Limited range of services,United States,California,Inglewood,90303,"33.936291, -118.332639",33.936291,-118.332639
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,Yes,1,...,2793,Price,Extra data charges,United States,California,Whittier,90602,"33.972119, -118.020188",33.972119,-118.020188

In [23]:
df.isnull().sum()[df.isnull().sum() > 0]

Offer             3877
Internet Type     1526
Churn Category    5174
Churn Reason      5174
dtype: int64

In [24]:
df['Offer'] = df['Offer'].fillna('No Offer')
df['Internet Type'] = df['Internet Type'].fillna('No Internet')
df['Churn Category'] = df['Churn Category'].fillna('No Churn')
df['Churn Reason'] = df['Churn Reason'].fillna('No Churn')

df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

In [26]:
df.to_csv('..\\data\\processed\\master_df.csv', index=False)

##### Next notebook --> 02 EDA(Exploratory Dataset Analysis)